volumes:
  caddy_data:
  caddy_config:

services:
  app:
    image: "${PROJECT_NAME}/franken-php:1.0"
    build:
      context: ./franken-php
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}_franken-php"
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    restart: unless-stopped
    environment:
      PHP_MEMORY_LIMIT: "${PHP_MEMORY_LIMIT}"
      PHP_IDE_CONFIG: serverName=gravity
      XDEBUG_CONFIG: idekey=PHPSTORM
      COMPOSER_MEMORY_LIMIT: '-1'
    volumes:
      - ${APP_SRC}:/var/www
      - ./franken-php/caddy_data:/data # - caddy_data:/data
      - ./franken-php/caddy_config:/config # - caddy_config:/config
    networks:
      - backend

  mysql:
    container_name: "${PROJECT_NAME}_mysql"
    image: "${PROJECT_NAME}/mysql:1.0"
    build: ./mysql
    volumes:
      - ./mysql/data/project_db:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: ${TIMEZONE}
    networks:
      - backend

  test_db:
    container_name: "${PROJECT_NAME}_test_db"
    image: "${PROJECT_NAME}/test_db:1.0"
    build: ./mysql
    volumes:
      - ./mysql/data/test_db:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: ${TIMEZONE}
    networks:
      - backend

  pma:
    container_name: "${PROJECT_NAME}_pma"
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8090:80"
    networks:
      - backend
    depends_on:
      - mysql

  mailhog:
    build: ./mail-hog
    image: "${PROJECT_NAME}/mail-hog:1.0"
    container_name: "${PROJECT_NAME}_mail-hog"
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - backend

networks:
  backend:
    driver: bridge
